AGG_STOCK_SWING_REALISED_PORTFOLIO_VIEW = '''
CREATE VIEW AGG_STOCK_SWING_REALISED_PORTFOLIO_VIEW AS
SELECT
    SSRPV.STOCK_NAME                                      AS STOCK_NAME
    ,SSRPV.OPENING_FEE_ID                                 AS OPENING_FEE_ID
    ,SSRPV.CLOSING_FEE_ID                                 AS CLOSING_FEE_ID
    ,SSRPV.TRADE_OPEN_DATE                                AS TRADE_OPEN_DATE
    ,SSRPV.TRADE_CLOSE_DATE                               AS TRADE_CLOSE_DATE
    ,OPEN_STOCK_QUANTITY_CALC.OPENING_STOCK_QUANTITY      AS AGG_OPENING_STOCK_QUANTITY
    ,CLOSE_STOCK_QUANTITY_CALC.CLOSING_STOCK_QUANTITY     AS AGG_CLOSING_STOCK_QUANTITY
    ,OPEN_STOCK_QUANTITY_CALC.OPENING_STOCK_QUANTITY -
     CLOSE_STOCK_QUANTITY_CALC.CLOSING_STOCK_QUANTITY     AS REMAINING_STOCK_BALANCE
    ,CASE WHEN
     OPEN_STOCK_QUANTITY_CALC.OPENING_STOCK_QUANTITY -
     CLOSE_STOCK_QUANTITY_CALC.CLOSING_STOCK_QUANTITY = 0
     THEN 'TRADES_COMPLETELY_CLOSED'
     ELSE 'TRADES_PARTIALLY_CLOSED' END                   AS TRADES_CLOSE_STATUS
    ,OPEN_STOCK_QUANTITY_CALC.OPENING_BUY_PRICE           AS AGG_OPENING_BUY_PRICE
    ,CLOSE_STOCK_QUANTITY_CALC.CLOSING_SELL_PRICE         AS AGG_CLOSING_SELL_PRICE
    ,ROUND(CLOSE_STOCK_QUANTITY_CALC.CLOSING_SELL_PRICE -
     OPEN_STOCK_QUANTITY_CALC.OPENING_BUY_PRICE,4)        AS "AGG_P/L"
    ,ROUND((CLOSE_STOCK_QUANTITY_CALC.CLOSING_SELL_PRICE -
     OPEN_STOCK_QUANTITY_CALC.OPENING_BUY_PRICE)/
     OPEN_STOCK_QUANTITY_CALC.OPENING_BUY_PRICE * 100,2)  AS "AGG_%_P/L"           
FROM
    STOCK_SWING_REALISED_PORTFOLIO_VIEW SSRPV
INNER JOIN
(
SELECT
    OPEN_INNER.STOCK_NAME                                 AS STOCK_NAME
    ,OPEN_INNER.OPENING_FEE_ID                            AS OPENING_FEE_ID
    ,SUM(OPEN_INNER.OPENING_STOCK_QUANTITY)               AS OPENING_STOCK_QUANTITY
    ,ROUND(SUM(OPEN_INNER.OPENING_BUY_PRICE),4)           AS OPENING_BUY_PRICE
FROM
(
SELECT
    OPEN_INFO.STOCK_NAME                                  AS STOCK_NAME
    ,OPEN_INFO.OPENING_TRADE_ID                           AS OPENING_TRADE_ID
    ,OPEN_INFO.OPENING_FEE_ID                             AS OPENING_FEE_ID
    ,MAX(OPEN_INFO.OPENING_STOCK_QUANTITY)                AS OPENING_STOCK_QUANTITY
    ,MAX(OPEN_INFO.BUY_PRICE)                             AS OPENING_BUY_PRICE_PER_UNIT
    ,ROUND(MAX(OPEN_INFO.OPENING_STOCK_QUANTITY) *
     MAX(OPEN_INFO.BUY_PRICE),4)                          AS OPENING_BUY_PRICE
FROM
    STOCK_SWING_REALISED_PORTFOLIO_VIEW OPEN_INFO
GROUP BY 1,2,3
) OPEN_INNER
) OPEN_STOCK_QUANTITY_CALC
ON
    SSRPV.OPENING_FEE_ID = OPEN_STOCK_QUANTITY_CALC.OPENING_FEE_ID
INNER JOIN
(
SELECT
    CLOSE_INNER.STOCK_NAME                                AS STOCK_NAME
    ,CLOSE_INNER.CLOSING_FEE_ID                           AS CLOSING_FEE_ID
    ,SUM(CLOSE_INNER.CLOSING_STOCK_QUANTITY)              AS CLOSING_STOCK_QUANTITY
    ,ROUND(SUM(CLOSE_INNER.CLOSING_SELL_PRICE),4)         AS CLOSING_SELL_PRICE
FROM
(
SELECT
    CLOSE_INFO.STOCK_NAME                                 AS STOCK_NAME
    ,CLOSE_INFO.CLOSING_TRADE_ID                          AS CLOSING_TRADE_ID
    ,CLOSE_INFO.CLOSING_FEE_ID                            AS CLOSING_FEE_ID
    ,MAX(CLOSE_INFO.CLOSING_STOCK_QUANTITY)               AS CLOSING_STOCK_QUANTITY
    ,MAX(CLOSE_INFO.SELL_PRICE)                           AS CLOSING_SELL_PRICE_PER_UNIT
    ,ROUND(MAX(CLOSE_INFO.CLOSING_STOCK_QUANTITY) *
     MAX(CLOSE_INFO.SELL_PRICE),4)                        AS CLOSING_SELL_PRICE
FROM
    STOCK_SWING_REALISED_PORTFOLIO_VIEW CLOSE_INFO
GROUP BY 1,2,3
) CLOSE_INNER
) CLOSE_STOCK_QUANTITY_CALC
ON
    SSRPV.CLOSING_FEE_ID = CLOSE_STOCK_QUANTITY_CALC.CLOSING_FEE_ID
GROUP BY 1,2,3,4,5,6,7,8,9,10,11
ORDER BY 4,5,1
;
'''