AGG_CONSOLIDATED_PORTFOLIO_VIEW = '''
CREATE VIEW AGG_CONSOLIDATED_PORTFOLIO_VIEW AS
SELECT
    CPV_UNREALISED.PORTFOLIO_TYPE                                                     AS PORTFOLIO_TYPE
    ,(SELECT DISTINCT PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD 
     IN ('MF_PROC','STOCK_PROC'))                                                     AS PROCESSING_DATE
    ,(SELECT DISTINCT PREV_PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD 
     IN ('MF_PROC','STOCK_PROC'))                                                     AS PREVIOUS_PROCESSING_DATE
    ,(SELECT DISTINCT NEXT_PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD 
     IN ('MF_PROC','STOCK_PROC'))                                                     AS NEXT_PROCESSING_DATE
    ,CPV_UNREALISED.INVESTED_AMOUNT                                                   AS AGG_INVESTED_AMOUNT
    ,CPV_UNREALISED.CURRENT_VALUE                                                     AS AGG_CURRENT_VALUE
    ,CPV_UNREALISED.PREVIOUS_VALUE                                                    AS AGG_PREVIOUS_VALUE
    ,CPV_UNREALISED."TOTAL_P/L"                                                       AS "AGG_TOTAL_P/L"
    ,CPV_UNREALISED."DAY_P/L"                                                         AS "AGG_DAY_P/L"
    ,CPV_UNREALISED."%_TOTAL_P/L"                                                     AS "%_AGG_TOTAL_P/L"
    ,CPV_UNREALISED."%_DAY_P/L"                                                       AS "%_AGG_DAY_P/L"
FROM
    CONSOLIDATED_RETURNS CPV_UNREALISED
WHERE
    CPV_UNREALISED.PORTFOLIO_TYPE          NOT IN ('Intraday Stocks', 'Realised Swing Stocks')
    AND CPV_UNREALISED.PROCESSING_DATE     = (SELECT DISTINCT PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD IN ('MF_PROC','STOCK_PROC'))
    AND CPV_UNREALISED.RECORD_DELETED_FLAG = 0

UNION ALL

SELECT
    CPV_INTRADAY.PORTFOLIO_TYPE                                                       AS PORTFOLIO_TYPE
    ,(SELECT PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD = 'STOCK_PROC')         AS PROCESSING_DATE
    ,(SELECT PREV_PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD = 'STOCK_PROC')    AS PREVIOUS_PROCESSING_DATE
    ,(SELECT NEXT_PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD = 'STOCK_PROC')    AS NEXT_PROCESSING_DATE
    ,ROUND(MAX(CPV_INTRADAY.INVESTED_AMOUNT),4)                                       AS AGG_INVESTED_AMOUNT
    ,ROUND(MAX(CPV_INTRADAY.INVESTED_AMOUNT) +  SUM(CPV_INTRADAY."TOTAL_P/L"),4)      AS AGG_CURRENT_VALUE
    ,0                                                                                AS AGG_PREVIOUS_VALUE
    ,ROUND(SUM(CPV_INTRADAY."TOTAL_P/L"),4)                                           AS "AGG_TOTAL_P/L"
    ,ROUND(SUM(CPV_INTRADAY."DAY_P/L"),4)                                             AS "AGG_DAY_P/L"
    ,ROUND(SUM(CPV_INTRADAY."TOTAL_P/L")/MAX(CPV_INTRADAY.INVESTED_AMOUNT) * 100,2)   AS "%_AGG_TOTAL_P/L"
    ,ROUND(SUM(CPV_INTRADAY."TOTAL_P/L")/MAX(CPV_INTRADAY.INVESTED_AMOUNT) * 100,2)   AS "%_AGG_DAY_P/L"
FROM
    CONSOLIDATED_RETURNS CPV_INTRADAY
WHERE
    CPV_INTRADAY.PORTFOLIO_TYPE = 'Intraday Stocks'
    AND (SELECT DISTINCT PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD ='STOCK_PROC') BETWEEN CPV_INTRADAY.START_DATE AND CPV_INTRADAY.END_DATE
    AND CPV_INTRADAY.RECORD_DELETED_FLAG = 0
GROUP BY 1

UNION ALL

SELECT
    CPV_REALISED.PORTFOLIO_TYPE                                                       AS PORTFOLIO_TYPE
    ,(SELECT PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD = 'STOCK_PROC')         AS PROCESSING_DATE
    ,(SELECT PREV_PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD = 'STOCK_PROC')    AS PREVIOUS_PROCESSING_DATE
    ,(SELECT NEXT_PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD = 'STOCK_PROC')    AS NEXT_PROCESSING_DATE
    ,ROUND(SUM(CPV_REALISED.INVESTED_AMOUNT),4)                                       AS AGG_INVESTED_AMOUNT
    ,ROUND(SUM(CPV_REALISED.CURRENT_VALUE),4)                                         AS AGG_CURRENT_VALUE
    ,0                                                                                AS AGG_PREVIOUS_VALUE
    ,ROUND(SUM(CPV_REALISED."TOTAL_P/L"),4)                                           AS "AGG_TOTAL_P/L"
    ,ROUND(SUM(CPV_REALISED."DAY_P/L"),4)                                             AS "AGG_DAY_P/L"
    ,ROUND(SUM(CPV_REALISED."TOTAL_P/L")/SUM(CPV_REALISED.INVESTED_AMOUNT) * 100,2)   AS "%_AGG_TOTAL_P/L"
    ,ROUND(SUM(CPV_REALISED."TOTAL_P/L")/SUM(CPV_REALISED.INVESTED_AMOUNT) * 100,2)   AS "%_AGG_DAY_P/L"
FROM
    CONSOLIDATED_RETURNS CPV_REALISED
WHERE
    CPV_REALISED.PORTFOLIO_TYPE = 'Realised Swing Stocks'
    AND (SELECT DISTINCT PROC_DATE FROM PROCESSING_DATE WHERE PROC_TYP_CD = 'STOCK_PROC') BETWEEN CPV_REALISED.START_DATE AND CPV_REALISED.END_DATE
    AND CPV_REALISED.RECORD_DELETED_FLAG = 0
GROUP BY 1
;
'''