FIN_STOCK_SWING_REALISED_PORTFOLIO_VIEW = '''
CREATE VIEW FIN_STOCK_SWING_REALISED_PORTFOLIO_VIEW AS
SELECT
    INNER_SUB.STOCK_NAME                                  AS STOCK_NAME
    ,INNER_SUB.OPENING_FEE_ID                             AS OPENING_FEE_ID
    ,INNER_SUB.CLOSING_FEE_ID                             AS CLOSING_FEE_ID
    ,INNER_SUB.TRADE_OPEN_DATE                            AS TRADE_OPEN_DATE
    ,INNER_SUB.TRADE_CLOSE_DATE                           AS TRADE_CLOSE_DATE
    ,INNER_SUB.AGG_OPENING_STOCK_QUANTITY                 AS AGG_OPENING_STOCK_QUANTITY
    ,INNER_SUB.AGG_CLOSING_STOCK_QUANTITY                 AS AGG_CLOSING_STOCK_QUANTITY
    ,INNER_SUB.REMAINING_STOCK_BALANCE                    AS REMAINING_STOCK_BALANCE
    ,INNER_SUB.TRADES_CLOSE_STATUS                        AS TRADES_CLOSE_STATUS
    ,INNER_SUB.AGG_OPENING_BUY_PRICE                      AS AGG_OPENING_BUY_PRICE
    ,INNER_SUB.OPEN_NET_OBLIGATION                        AS OPEN_NET_OBLIGATION
    ,CASE WHEN ABS(ROUND(INNER_SUB.AGG_OPENING_BUY_PRICE,4))
     = ABS(ROUND(INNER_SUB.OPEN_NET_OBLIGATION,4))
          THEN 'Open_Matched'
     ELSE 'Open_Unmatched' END                            AS OPEN_MATCH_STATUS
    ,INNER_SUB.OPEN_TOTAL_BROKERAGE                       AS OPEN_TOTAL_BROKERAGE
    ,INNER_SUB.OPEN_TOTAL_CHARGES                         AS OPEN_TOTAL_CHARGES
    ,INNER_SUB.OPEN_TOTAL_FEES                            AS OPEN_TOTAL_FEES
    ,INNER_SUB.AGG_CLOSING_SELL_PRICE                     AS AGG_CLOSING_SELL_PRICE
    ,INNER_SUB.CLOSE_NET_OBLIGATION                       AS CLOSE_NET_OBLIGATION
    ,CASE WHEN ABS(ROUND(INNER_SUB.AGG_CLOSING_SELL_PRICE,4))
     = ABS(ROUND(INNER_SUB.CLOSE_NET_OBLIGATION,4))
          THEN 'Close_Matched'
     ELSE 'Close_Unmatched' END                           AS CLOSE_MATCH_STATUS
    ,INNER_SUB.CLOSE_TOTAL_BROKERAGE                      AS CLOSE_TOTAL_BROKERAGE
    ,INNER_SUB.CLOSE_TOTAL_CHARGES                        AS CLOSE_TOTAL_CHARGES
    ,INNER_SUB.CLOSE_TOTAL_FEES                           AS CLOSE_TOTAL_FEES
    ,INNER_SUB.OPEN_TOTAL_FEES + 
     INNER_SUB.CLOSE_TOTAL_FEES                           AS TOTAL_FEES
    ,INNER_SUB."AGG_P/L"                                  AS "AGG_P/L"
    ,INNER_SUB."AGG_%_P/L"                                AS "AGG_%_P/L"
    ,ROUND(INNER_SUB."AGG_P/L" - INNER_SUB.OPEN_TOTAL_FEES
     - INNER_SUB.CLOSE_TOTAL_FEES,4)                      AS "NET_P/L"
    ,ROUND((INNER_SUB."AGG_P/L" - INNER_SUB.OPEN_TOTAL_FEES
     - INNER_SUB.CLOSE_TOTAL_FEES) / 
     INNER_SUB.AGG_OPENING_BUY_PRICE * 100,2)             AS "NET_%_P/L"
    ,INNER_SUB.PROCESSING_DATE                            AS PROCESSING_DATE
    ,INNER_SUB.PREVIOUS_PROCESSING_DATE                   AS PREVIOUS_PROCESSING_DATE
    ,INNER_SUB.NEXT_PROCESSING_DATE                       AS NEXT_PROCESSING_DATE
FROM
(
SELECT
    ASSRPV.STOCK_NAME                                     AS STOCK_NAME
    ,ASSRPV.OPENING_FEE_ID                                AS OPENING_FEE_ID
    ,ASSRPV.CLOSING_FEE_ID                                AS CLOSING_FEE_ID
    ,ASSRPV.TRADE_OPEN_DATE                               AS TRADE_OPEN_DATE
    ,ASSRPV.TRADE_CLOSE_DATE                              AS TRADE_CLOSE_DATE
    ,ASSRPV.AGG_OPENING_STOCK_QUANTITY                    AS AGG_OPENING_STOCK_QUANTITY
    ,ASSRPV.AGG_CLOSING_STOCK_QUANTITY                    AS AGG_CLOSING_STOCK_QUANTITY
    ,ASSRPV.REMAINING_STOCK_BALANCE                       AS REMAINING_STOCK_BALANCE
    ,ASSRPV.TRADES_CLOSE_STATUS                           AS TRADES_CLOSE_STATUS
    ,ASSRPV.AGG_OPENING_BUY_PRICE                         AS AGG_OPENING_BUY_PRICE
    ,ASSRPV.AGG_CLOSING_SELL_PRICE                        AS AGG_CLOSING_SELL_PRICE
    ,ASSRPV."AGG_P/L"                                     AS "AGG_P/L"
    ,ASSRPV."AGG_%_P/L"                                   AS "AGG_%_P/L"
    ,OPEN_FEE.NET_OBLIGATION                              AS OPEN_NET_OBLIGATION
    ,OPEN_FEE.BROKERAGE                                   AS OPEN_BROKERAGE
    ,OPEN_FEE.EXCHANGE_TRANSACTION_CHARGES                AS OPEN_EXCHANGE_TRANSACTION_CHARGES
    ,OPEN_FEE.IGST                                        AS OPEN_IGST
    ,OPEN_FEE.SECURITIES_TRANSACTION_TAX                  AS OPEN_SECURITIES_TRANSACTION_TAX
    ,OPEN_FEE.SEBI_TURN_OVER_FEES                         AS OPEN_SEBI_TURN_OVER_FEES
    ,OPEN_FEE.AUTO_SQUARE_OFF_CHARGES                     AS OPEN_AUTO_SQUARE_OFF_CHARGES
    ,OPEN_FEE.DEPOSITORY_CHARGES                          AS OPEN_DEPOSITORY_CHARGES
    ,ROUND(OPEN_FEE.BROKERAGE +
     OPEN_FEE.EXCHANGE_TRANSACTION_CHARGES +
     OPEN_FEE.IGST + OPEN_FEE.SECURITIES_TRANSACTION_TAX 
     + OPEN_FEE.SEBI_TURN_OVER_FEES,4)                    AS OPEN_TOTAL_BROKERAGE
    ,ROUND(OPEN_FEE.AUTO_SQUARE_OFF_CHARGES + 
     OPEN_FEE.DEPOSITORY_CHARGES,4)                       AS OPEN_TOTAL_CHARGES
    ,ROUND(OPEN_FEE.BROKERAGE +
     OPEN_FEE.EXCHANGE_TRANSACTION_CHARGES +
     OPEN_FEE.IGST + OPEN_FEE.SECURITIES_TRANSACTION_TAX 
     + OPEN_FEE.SEBI_TURN_OVER_FEES +
     OPEN_FEE.AUTO_SQUARE_OFF_CHARGES
     + OPEN_FEE.DEPOSITORY_CHARGES,4)                     AS OPEN_TOTAL_FEES
    ,CLOSE_FEE.NET_OBLIGATION                             AS CLOSE_NET_OBLIGATION
    ,CLOSE_FEE.BROKERAGE                                  AS CLOSE_BROKERAGE
    ,CLOSE_FEE.EXCHANGE_TRANSACTION_CHARGES               AS CLOSE_EXCHANGE_TRANSACTION_CHARGES
    ,CLOSE_FEE.IGST                                       AS CLOSE_IGST
    ,CLOSE_FEE.SECURITIES_TRANSACTION_TAX                 AS CLOSE_SECURITIES_TRANSACTION_TAX
    ,CLOSE_FEE.SEBI_TURN_OVER_FEES                        AS CLOSE_SEBI_TURN_OVER_FEES
    ,CLOSE_FEE.AUTO_SQUARE_OFF_CHARGES                    AS CLOSE_AUTO_SQUARE_OFF_CHARGES
    ,CLOSE_FEE.DEPOSITORY_CHARGES                         AS CLOSE_DEPOSITORY_CHARGES
    ,ROUND(CLOSE_FEE.BROKERAGE +
     CLOSE_FEE.EXCHANGE_TRANSACTION_CHARGES +
     CLOSE_FEE.IGST + CLOSE_FEE.SECURITIES_TRANSACTION_TAX 
     + CLOSE_FEE.SEBI_TURN_OVER_FEES,4)                   AS CLOSE_TOTAL_BROKERAGE
    ,ROUND(CLOSE_FEE.AUTO_SQUARE_OFF_CHARGES + 
     CLOSE_FEE.DEPOSITORY_CHARGES,4)                      AS CLOSE_TOTAL_CHARGES
    ,ROUND(CLOSE_FEE.BROKERAGE +
     CLOSE_FEE.EXCHANGE_TRANSACTION_CHARGES +
     CLOSE_FEE.IGST + CLOSE_FEE.SECURITIES_TRANSACTION_TAX 
     + CLOSE_FEE.SEBI_TURN_OVER_FEES + 
     + CLOSE_FEE.AUTO_SQUARE_OFF_CHARGES +
     CLOSE_FEE.DEPOSITORY_CHARGES,4)                      AS CLOSE_TOTAL_FEES
    ,ASSRPV.PROCESSING_DATE                               AS PROCESSING_DATE
    ,ASSRPV.PREVIOUS_PROCESSING_DATE                      AS PREVIOUS_PROCESSING_DATE
    ,ASSRPV.NEXT_PROCESSING_DATE                          AS NEXT_PROCESSING_DATE
FROM
    AGG_STOCK_SWING_REALISED_PORTFOLIO_VIEW ASSRPV
LEFT OUTER JOIN
    FEE_COMPONENT OPEN_FEE
ON
    OPEN_FEE.FEE_ID = ASSRPV.OPENING_FEE_ID
LEFT OUTER JOIN
    FEE_COMPONENT CLOSE_FEE
ON
    CLOSE_FEE.FEE_ID = ASSRPV.CLOSING_FEE_ID
) INNER_SUB
;
'''