FIN_MUTUAL_FUND_PORTFOLIO_VIEW = '''
CREATE VIEW FIN_MUTUAL_FUND_PORTFOLIO_VIEW AS
SELECT
    ROUND(SUM(AMFPV."AGG_P/L"),4)                     AS "FIN_P/L"
    ,ROUND(SUM(AMFPV.AGG_AMC_AMOUNT),4)               AS "FIN_AMC_AMOUNT"
    ,ROUND(SUM(AMFPV.AGG_CURRENT_AMOUNT),4)           AS "FIN_CURRENT_AMOUNT"
    ,ROUND(SUM(AMFPV.AGG_PREVIOUS_AMOUNT),4)          AS "FIN_PREVIOUS_AMOUNT"
    ,ROUND(ROUND(SUM(AMFPV."AGG_P/L"),4) /
    ROUND(SUM(AMFPV.AGG_AMC_AMOUNT),4) * 100,4)       AS "FIN_%P/L"
    ,ROUND(SUM(AMFPV."AGG_DAY_P/L"),4)                AS "FIN_DAY_P/L"
    ,ROUND(ROUND(SUM(AMFPV."AGG_DAY_P/L"),4) /
    ROUND(SUM(AMFPV.AGG_PREVIOUS_AMOUNT),4),6) * 100  AS "FIN_%DAY_P/L"
FROM
    AGG_MUTUAL_FUND_PORTFOLIO_VIEW AMFPV;
'''